#index:
#  path: /
#  controller: App\Controller\HomepageController::listAction
#
#location_list:
#  path: /location
#  controller: App\Controller\LocationsController::listAction
#
#location:
#  path: /location/{slug}
#  controller: App\Controller\LocationController::localAction
#
#property_list:
#  path: /property
#  controller: App\Controller\PropertyController::listAction
#
#property:
#  path: /property/{id}
#  controller: App\Controller\PropertyController::propertyAction